"""
Zentrale Pfade des Prototyps.

Die Pfade werden aus der Position dieser Datei abgeleitet. Dadurch müssen
Apps, Worker, Experimente und Pipeline-Helfer die Projektstruktur nicht
jeweils selbst rekonstruieren.
"""

from pathlib import Path

from prototype.shared.constants import (
    DIR_APPS,
    DIR_CACHE,
    DIR_CHUNKING_EXPERIMENT,
    DIR_CONFIG,
    DIR_DASHBOARDS,
    DIR_DATA,
    DIR_EXPERIMENTS,
    DIR_INQUIRIES,
    DIR_KNOWLEDGE_BASE,
    DIR_MODELS,
    DIR_OPERATIONS_OUTPUTS,
    DIR_OUTPUTS,
    DIR_PIPELINES,
    DIR_PYCACHE,
    DIR_SHARED,
    DIR_SRC,
    DIR_TESTS,
    DIR_V0,
    DIR_V0_ALPHA,
    DIR_V1,
    DIR_V2,
    DIR_V3,
    DIR_V4,
    DIR_V5,
    ENV_FILE_NAME,
    FILENAME_CASES_STORE,
    FILENAME_CHUNKING_EXPERIMENT_CONFIG_JSON,
    FILENAME_CHUNKING_METRICS_JSON,
    FILENAME_CHUNKING_RESULTS_CSV,
    FILENAME_CHUNKING_SUMMARY_CSV,
    FILENAME_DASHBOARD_METRICS,
    FILENAME_INQUIRIES_20,
    FILENAME_INQUIRIES_80,
    FILENAME_LAST_RUN,
    FILENAME_METRICS,
    FILENAME_MONITORING,
    FILENAME_MUNICIPALITY_CONFIG,
    FILENAME_MUNICIPALITY_V2_CONFIG,
    FILENAME_PROCESSED_EMAILS_STORE,
    FILENAME_RUNTIME_STATE,
    FILENAME_V0_ALPHA_RESULTS_CSV,
    FILENAME_V0_RESULTS_CSV,
    FILENAME_V1_CONFIG_JSON,
    FILENAME_V1_METRICS_JSON,
    FILENAME_V1_RESULTS_CSV,
    FILENAME_V2_CONFIG_JSON,
    FILENAME_V2_METRICS_JSON,
    FILENAME_V2_RESULTS_CSV,
    FILENAME_V3_AUDIT_LOG_JSONL,
    FILENAME_V3_CONFIG_JSON,
    FILENAME_V3_METRICS_JSON,
    FILENAME_V3_RESULTS_CSV,
    FILENAME_V4_AUDIT_LOG_JSONL,
    FILENAME_V4_CONFIG_JSON,
    FILENAME_V4_METRICS_JSON,
    FILENAME_V4_MONITORING_CSV,
    FILENAME_V4_RESULTS_CSV,
    FILENAME_V5_AUDIT_LOG_JSONL,
    FILENAME_V5_CONFIG_JSON,
    FILENAME_V5_METRICS_JSON,
    FILENAME_V5_RESULTS_CSV,
    FILENAME_WORKER_STATUS_STORE,
    KNOWLEDGE_BASE_VERSION_V2,
    KNOWLEDGE_BASE_VERSION_V3,
    KNOWLEDGE_BASE_VERSION_V4,
    KNOWLEDGE_BASE_VERSION_V5,
    MODEL_ALL_MINILM_L6_V2, FILENAME_MODEL_PROFILES,
)


PROTOTYPE_DIR = Path(__file__).resolve().parents[1]
PROJECT_ROOT = PROTOTYPE_DIR.parent

ENV_PATH = PROJECT_ROOT / ENV_FILE_NAME

APPS_DIR = PROTOTYPE_DIR / DIR_APPS
CONFIG_DIR = PROTOTYPE_DIR / DIR_CONFIG
DASHBOARDS_DIR = PROTOTYPE_DIR / DIR_DASHBOARDS
DATA_DIR = PROTOTYPE_DIR / DIR_DATA
EXPERIMENTS_DIR = PROTOTYPE_DIR / DIR_EXPERIMENTS
MODELS_DIR = PROTOTYPE_DIR / DIR_MODELS
OUTPUTS_DIR = PROTOTYPE_DIR / DIR_OUTPUTS
PIPELINES_DIR = PROTOTYPE_DIR / DIR_PIPELINES
SHARED_DIR = PROTOTYPE_DIR / DIR_SHARED
SRC_DIR = PROTOTYPE_DIR / DIR_SRC
TESTS_DIR = PROTOTYPE_DIR / DIR_TESTS

INQUIRIES_DIR = DATA_DIR / DIR_INQUIRIES
KNOWLEDGE_BASE_DIR = DATA_DIR / DIR_KNOWLEDGE_BASE

MUNICIPALITY_CONFIG_PATH = CONFIG_DIR / FILENAME_MUNICIPALITY_CONFIG
MUNICIPALITY_V2_CONFIG_PATH = CONFIG_DIR / FILENAME_MUNICIPALITY_V2_CONFIG
MODEL_PROFILES_PATH = CONFIG_DIR / FILENAME_MODEL_PROFILES

LEGACY_MUNICIPALITY_CONFIG_PATH = MUNICIPALITY_CONFIG_PATH
V5_MUNICIPALITY_CONFIG_PATH = MUNICIPALITY_V2_CONFIG_PATH
DEFAULT_MUNICIPALITY_CONFIG_PATH = V5_MUNICIPALITY_CONFIG_PATH


def municipality_config_path_for_version(version: str) -> Path:
    normalized_version = str(version or "").strip().upper()

    if normalized_version in {"V1", "V2", "V3", "V4"}:
        return LEGACY_MUNICIPALITY_CONFIG_PATH

    return V5_MUNICIPALITY_CONFIG_PATH


def knowledge_base_path_for_version(version: str) -> Path:
    normalized_version = str(version or "").strip().upper()

    if normalized_version == "V5":
        return KNOWLEDGE_BASE_V5_PATH

    return KNOWLEDGE_BASE_V4_PATH

INQUIRIES_20_PATH = INQUIRIES_DIR / FILENAME_INQUIRIES_20
INQUIRIES_80_PATH = INQUIRIES_DIR / FILENAME_INQUIRIES_80
DEFAULT_TESTSET_PATH = INQUIRIES_20_PATH

KNOWLEDGE_BASE_V2_PATH = KNOWLEDGE_BASE_DIR / KNOWLEDGE_BASE_VERSION_V2
KNOWLEDGE_BASE_V3_PATH = KNOWLEDGE_BASE_DIR / KNOWLEDGE_BASE_VERSION_V3
KNOWLEDGE_BASE_V4_PATH = KNOWLEDGE_BASE_DIR / KNOWLEDGE_BASE_VERSION_V4
KNOWLEDGE_BASE_V5_PATH = KNOWLEDGE_BASE_DIR / KNOWLEDGE_BASE_VERSION_V5

DEFAULT_KNOWLEDGE_BASE_PATH = KNOWLEDGE_BASE_V5_PATH

LOCAL_EMBEDDING_MODEL_PATH = MODELS_DIR / MODEL_ALL_MINILM_L6_V2

V0_OUTPUT_DIR = OUTPUTS_DIR / DIR_V0
V0_ALPHA_OUTPUT_DIR = OUTPUTS_DIR / DIR_V0_ALPHA
V1_OUTPUT_DIR = OUTPUTS_DIR / DIR_V1
V2_OUTPUT_DIR = OUTPUTS_DIR / DIR_V2
V3_OUTPUT_DIR = OUTPUTS_DIR / DIR_V3
V4_OUTPUT_DIR = OUTPUTS_DIR / DIR_V4
V5_OUTPUT_DIR = OUTPUTS_DIR / DIR_V5

V0_RESULTS_CSV_PATH = V0_OUTPUT_DIR / FILENAME_V0_RESULTS_CSV
V0_ALPHA_RESULTS_CSV_PATH = V0_ALPHA_OUTPUT_DIR / FILENAME_V0_ALPHA_RESULTS_CSV

V1_RESULTS_CSV_PATH = V1_OUTPUT_DIR / FILENAME_V1_RESULTS_CSV
V1_METRICS_JSON_PATH = V1_OUTPUT_DIR / FILENAME_V1_METRICS_JSON
V1_CONFIG_JSON_PATH = V1_OUTPUT_DIR / FILENAME_V1_CONFIG_JSON

V2_RESULTS_CSV_PATH = V2_OUTPUT_DIR / FILENAME_V2_RESULTS_CSV
V2_METRICS_JSON_PATH = V2_OUTPUT_DIR / FILENAME_V2_METRICS_JSON
V2_CONFIG_JSON_PATH = V2_OUTPUT_DIR / FILENAME_V2_CONFIG_JSON

V3_RESULTS_CSV_PATH = V3_OUTPUT_DIR / FILENAME_V3_RESULTS_CSV
V3_METRICS_JSON_PATH = V3_OUTPUT_DIR / FILENAME_V3_METRICS_JSON
V3_CONFIG_JSON_PATH = V3_OUTPUT_DIR / FILENAME_V3_CONFIG_JSON
V3_AUDIT_LOG_JSONL_PATH = V3_OUTPUT_DIR / FILENAME_V3_AUDIT_LOG_JSONL

V4_RESULTS_CSV_PATH = V4_OUTPUT_DIR / FILENAME_V4_RESULTS_CSV
V4_METRICS_JSON_PATH = V4_OUTPUT_DIR / FILENAME_V4_METRICS_JSON
V4_CONFIG_JSON_PATH = V4_OUTPUT_DIR / FILENAME_V4_CONFIG_JSON
V4_MONITORING_CSV_PATH = V4_OUTPUT_DIR / FILENAME_V4_MONITORING_CSV
V4_AUDIT_LOG_JSONL_PATH = V4_OUTPUT_DIR / FILENAME_V4_AUDIT_LOG_JSONL

V5_RESULTS_CSV_PATH = V5_OUTPUT_DIR / FILENAME_V5_RESULTS_CSV
V5_METRICS_JSON_PATH = V5_OUTPUT_DIR / FILENAME_V5_METRICS_JSON
V5_CONFIG_JSON_PATH = V5_OUTPUT_DIR / FILENAME_V5_CONFIG_JSON
V5_AUDIT_LOG_JSONL_PATH = V5_OUTPUT_DIR / FILENAME_V5_AUDIT_LOG_JSONL

OPERATIONS_OUTPUT_DIR = OUTPUTS_DIR / DIR_OPERATIONS_OUTPUTS

CASES_PATH = OPERATIONS_OUTPUT_DIR / FILENAME_CASES_STORE
PROCESSED_EMAILS_PATH = OPERATIONS_OUTPUT_DIR / FILENAME_PROCESSED_EMAILS_STORE
WORKER_STATUS_PATH = OPERATIONS_OUTPUT_DIR / FILENAME_WORKER_STATUS_STORE

METRICS_PATH = OPERATIONS_OUTPUT_DIR / FILENAME_METRICS
MONITORING_PATH = OPERATIONS_OUTPUT_DIR / FILENAME_MONITORING
DASHBOARD_METRICS_PATH = OPERATIONS_OUTPUT_DIR / FILENAME_DASHBOARD_METRICS
LAST_RUN_PATH = OPERATIONS_OUTPUT_DIR / FILENAME_LAST_RUN
RUNTIME_STATE_PATH = OPERATIONS_OUTPUT_DIR / FILENAME_RUNTIME_STATE

OPERATIONS_CACHE_DIR = OPERATIONS_OUTPUT_DIR / DIR_CACHE
OPERATIONS_PYCACHE_DIR = OPERATIONS_OUTPUT_DIR / DIR_PYCACHE

CHUNKING_EXPERIMENT_OUTPUT_DIR = OUTPUTS_DIR / DIR_CHUNKING_EXPERIMENT
CHUNKING_RESULTS_CSV_PATH = CHUNKING_EXPERIMENT_OUTPUT_DIR / FILENAME_CHUNKING_RESULTS_CSV
CHUNKING_METRICS_JSON_PATH = CHUNKING_EXPERIMENT_OUTPUT_DIR / FILENAME_CHUNKING_METRICS_JSON
CHUNKING_SUMMARY_CSV_PATH = CHUNKING_EXPERIMENT_OUTPUT_DIR / FILENAME_CHUNKING_SUMMARY_CSV
CHUNKING_EXPERIMENT_CONFIG_JSON_PATH = (
    CHUNKING_EXPERIMENT_OUTPUT_DIR / FILENAME_CHUNKING_EXPERIMENT_CONFIG_JSON
)


def ensure_operations_output_dir() -> None:
    OPERATIONS_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def ensure_output_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def prototype_path(*parts: str) -> Path:
    return PROTOTYPE_DIR.joinpath(*parts)


def project_path(*parts: str) -> Path:
    return PROJECT_ROOT.joinpath(*parts)
